### ISSUE TITLE
CAT add_names returns KeyError: 'no taxid found (5EY5_A)'

### ISSUE THREAD

**Issue by ash-bell** [dutilh/CAT#10]
Hi,
I'm running the code `CAT add_names -i out.BAT.ORF2LCA.txt -o out.BAT.ORF2LCA.names.txt -t ../2018-10-16_taxonomy/` and it is returning me the error: 

# CAT v4.0.
[2018-10-22 11:46:36.384011] Importing file ../2018-10-16_taxonomy/nodes.dmp.
[2018-10-22 11:46:38.874349] Importing file ../2018-10-16_taxonomy/names.dmp.
[2018-10-22 11:46:40.758726] Appending names...
Traceback (most recent call last):
  File "/gpfs/ts0/home/bt273/BIOS-SCOPE/metag/ashley/data/CAT/CAT_pack/CAT", line 72, in <module>
    main()
  File "/gpfs/ts0/home/bt273/BIOS-SCOPE/metag/ashley/data/CAT/CAT_pack/CAT", line 60, in main
    add_names.run()
  File "/gpfs/ts0/projects/Research_Project-172179/metag/ashley/data/CAT/CAT_pack/add_names.py", line 174, in run
    add_names(args)
  File "/gpfs/ts0/projects/Research_Project-172179/metag/ashley/data/CAT/CAT_pack/add_names.py", line 163, in add_names
    scores)
  File "/gpfs/ts0/projects/Research_Project-172179/metag/ashley/data/CAT/CAT_pack/tax.py", line 235, in convert_to_names
    name = taxid2name[taxid]
KeyError: 'no taxid found (5EY5_A)'

I'm using Python 3.6.6
My Taxonomy file contains:
2018-10-16.prot.accession2taxid.gz
citations.dmp
division.dmp
gencode.dmp
names.dmp
readme.txt
2018-10-16.taxdump.tar.gz
delnodes.dmp
gc.prt
merged.dmp
nodes.dmp

I've used `CAT prepare --fresh` and `CAT bins` to assess my metagenome bins with no problems. 

Anyone have any ideas to where I'm going wrong?

**Comment by bastiaanvonmeijenfeldt** [comment]
I have uploaded a new version of the CAT pack (v4.0.1) that solves this bug. Thanks for noticing!
You don't need to run BAT again, just use the newest version to add names and all should be fine.

Hope this helps!

**Comment by ash-bell** [comment]
I'm still having the exact same problem with a fresh install of CAT 4.0.1
`$ CAT --version
CAT v4.0.1 (24th of October, 2018) by F. A. Bastiaan von Meijenfeldt.`

`$ CAT add_names -i out.BAT.ORF2LCA.txt -o out.BAT.ORF2LCA.names.txt -t ../2018-10-16_taxonomy/
# CAT v4.0.1.
[2018-10-25 15:07:33.458664] Importing file ../2018-10-16_taxonomy/nodes.dmp.
[2018-10-25 15:07:36.663179] Importing file ../2018-10-16_taxonomy/names.dmp.
[2018-10-25 15:07:38.845326] Appending names...
Traceback (most recent call last):
  File "/gpfs/ts0/home/bt273/BIOS-SCOPE/metag/ashley/data/CAT/CAT/CAT_pack/CAT", line 72, in <module>
    main()
  File "/gpfs/ts0/home/bt273/BIOS-SCOPE/metag/ashley/data/CAT/CAT/CAT_pack/CAT", line 60, in main
    add_names.run()
  File "/gpfs/ts0/projects/Research_Project-172179/metag/ashley/data/CAT/CAT/CAT_pack/add_names.py", line 181, in run
    add_names(args)
  File "/gpfs/ts0/projects/Research_Project-172179/metag/ashley/data/CAT/CAT/CAT_pack/add_names.py", line 170, in add_names
    scores)
  File "/gpfs/ts0/projects/Research_Project-172179/metag/ashley/data/CAT/CAT/CAT_pack/tax.py", line 235, in convert_to_names
    name = taxid2name[taxid]
KeyError: 'no taxid found (5EY5_A)'`

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi Ashley,

It turns out v4.0.1 only fixed the bug for CAT output files, not for BAT output files. I just uploaded v4.0.2, which should work on BAT output files as well. My apologies! Let me know if you still encounter problems.

Bastiaan
