### ISSUE TITLE
Errors in running RAT

### ISSUE THREAD

**Issue by dannyionescu** [dutilh/CAT#111]
Hi,

I am trying to run RAT on a series of samples.
At first I got an error during the CAT step, but I was able to provide cat with c2c files from a previous run.
Now the tool crashed at the bin set giving the error at the end of this verbose output:

[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 32 ./TRA10_S76.contigs.fa /scratch/dionescu/assemble/clean_reads/concat_paired/TRA10_S76_.R1.paired.fastq.gz /scratch/dionescu/assemble/clean_reads/concat_paired/TRA10_S76_.R2.paired.fastq.gz
[main] Real time: 454.442 sec; CPU: 9538.439 sec
[bam_sort_core] merging from 1 files and 32 in-memory blocks...
# CAT v6.0.

# Running command: reads --mode mcr -b ../bins -c TRA10_S76.contigs.fa -1 /scratch/dionescu/assemble/clean_reads/concat_paired/TRA10_S76_.R1.paired.fastq.gz -2 /scratch/dionescu/assemble/clean_reads/concat_paired/TRA10_S76_.R2.paired.fastq.gz -d /scratch/dionescu/CAT_NR_readyDB/db -t /scratch/dionescu/CAT_NR_readyDB/tax --c2c TRA10_S76.RAT.contig2classification.txt -n 32 --out_prefix TRA10_S76.RAT --force --verbose

[2024-02-18 15:06:11] samtools found: samtools 1.18.
[2024-02-18 15:06:11] bwa found: Version: 0.7.17-r1188.
[2024-02-18 15:06:11] Prodigal found: Prodigal V2.6.3: February, 2016.
[2024-02-18 15:06:11] DIAMOND found: diamond version 2.1.8.

RAT is running. Mapping reads against assembly with bwa mem.

[2024-02-18 15:06:11] Running bwa mem for read mapping. File ./TRA10_S76.RAT.TRA10_S76.contigs.fa.TRA10_S76_.R1.paired.fastq.gz.bwamem.sorted will be generated.Do not forget to cite bwa mem and samtools when using RAT in your publication!
[2024-02-18 15:06:11] Contigs fasta is already indexed.
[2024-02-18 15:06:11] Running bwa mem...
[2024-02-18 15:22:35] Sorting bam file...
[2024-02-18 15:41:07] Read mapping done!

[2024-02-18 15:41:07] contig2classification file supplied. Processing contig classifications.
[2024-02-18 15:41:07] Loading file /scratch/dionescu/CAT_NR_readyDB/tax/nodes.dmp.
[2024-02-18 15:41:09] Bin folder supplied. Processing bin folder.
**Traceback (most recent call last):
  File "/home/dionescu/CAT/CAT_pack/CAT/CAT_pack/CAT", line 102, in <module>
    main()
  File "/home/dionescu/CAT/CAT_pack/CAT/CAT_pack/CAT", line 86, in main
    reads.run()
  File "/home/dionescu/CAT/CAT_pack/CAT/CAT_pack/reads.py", line 318, in run
    bins=process_bin_folder(args.bin_folder, args.bin_suffix)
  File "/home/dionescu/CAT/CAT_pack/CAT/CAT_pack/reads.py", line 1309, in process_bin_folder
    if b.split('.')[-1]==bin_suffix.split('.')[-1] and not b.rsplit('.', 1)[0].endswith('unbinned'):
AttributeError: 'NoneType' object has no attribute 'split'**

The command I am using is:
for contig in TR*contigs.fa

do
        R1=$(basename $contig | sed 's/\.conti.*/_\.R1\.paired\.fastq\.gz/')
        R2=$(basename $contig | sed 's/\.conti.*/_\.R2\.paired\.fastq\.gz/')
        sample=$(basename $contig | sed 's/\.conti.*//')

        echo "starting RAT with $contig and $R1 $R2"

       /home/dionescu/CAT/CAT_pack/CAT/CAT_pack/CAT reads\
        --mode mcr\
        -b ../bins\
        -c $contig\
        -1 /scratch/dionescu/assemble/clean_reads/concat_paired/$R1\
        -2 /scratch/dionescu/assemble/clean_reads/concat_paired/$R2\
        -d /scratch/dionescu/CAT_NR_readyDB/db\
        -t /scratch/dionescu/CAT_NR_readyDB/tax\
        --c2c $sample.RAT.contig2classification.txt\
        -n $SLURM_CPUS_PER_TASK\
        --out_prefix $sample.RAT\
        --force\
        --verbose

done

This is the log file of one sample:

# CAT v6.0.

# Running command: reads --mode mcr -b ../bins -c TRA10_S76.contigs.fa -1 /scratch/dionescu/assemble/clean_reads/concat_paired/TRA10_S76_.R1.paired.fastq.gz -2 /scratch/dionescu/assemble/clean_reads/concat_paired/TRA10_S76_.R2.paired.fastq.gz -d /scratch/dionescu/CAT_NR_readyDB/db -t /scratch/dionescu/CAT_NR_readyDB/tax --c2c TRA10_S76.RAT.contig2classification.txt -n 32 --out_prefix TRA10_S76.RAT --force --verbose

[2024-02-18 15:06:11] samtools found: samtools 1.18.
[2024-02-18 15:06:11] bwa found: Version: 0.7.17-r1188.
[2024-02-18 15:06:11] Prodigal found: Prodigal V2.6.3: February, 2016.
[2024-02-18 15:06:11] DIAMOND found: diamond version 2.1.8.

RAT is running. Mapping reads against assembly with bwa mem.

[2024-02-18 15:06:11] Running bwa mem for read mapping. File ./TRA10_S76.RAT.TRA10_S76.contigs.fa.TRA10_S76_.R1.paired.fastq.gz.bwamem.sorted will be generated.Do not forget to cite bwa mem and samtools when using RAT in your publication!
[2024-02-18 15:06:11] Contigs fasta is already indexed.
[2024-02-18 15:06:11] Running bwa mem...
[2024-02-18 15:22:35] Sorting bam file...
[2024-02-18 15:41:07] Read mapping done!

[2024-02-18 15:41:07] contig2classification file supplied. Processing contig classifications.
[2024-02-18 15:41:07] Loading file /scratch/dionescu/CAT_NR_readyDB/tax/nodes.dmp.
[2024-02-18 15:41:09] Bin folder supplied. Processing bin folder.

The contig file is: TRA10_S76.contigs.fa
These are the files created for this sample:

TRA10_S76_.R1.paired.fastq.gz.bwamem.sorted
TRA10_S76.RAT.contig2classification.txt
TRA10_S76.RAT.log
TRA10_S76.contigs.fa.amb
TRA10_S76.contigs.fa.ann
TRA10_S76.contigs.fa.bwt
TRA10_S76.contigs.fa.pac
TRA10_S76.contigs.fa.sa

Note - just in case this is important - the bins I am running against are not specifically from this sample but from a bunch of different samples in this dataset. These are not from a coaasembly.

Please let me know what could be the issues.

Thanks

Danny

**Comment by dannyionescu** [comment]
It appears that the error may come from not supplying a suffix to the bin fasta files. This error does not appear after supplying the -s fa paramter.
