### ISSUE TITLE
IndexError: list index out of range when creating bin2classification.txt

### ISSUE THREAD

**Issue by wclose** [dutilh/CAT#32]
I'm using CAT to classify some viral MAGs and everything seems to run fine until it gets to the point of creating the summary file. Protein prediction, diamond alignment, etc. all work great until it starts creating the bin2classification file. In case it matters, I didn't use the full nr database but instead created my own out of the RefSeq viral database but followed all the instructions/looked through the CAT code to verify it would work so it should be compatible. Here is the log:

```
# CAT v5.0.3.

BAT is running. Protein prediction, alignment, and bin classification are carried out.
Rarw!

Supplied command: /home/wlclose/miniconda3/envs/catbat/bin/CAT bins -r 10 -f 0.1 --index_chunks 1 --block_size 6 --nproc 4 --sensitive -s .fa -b data/metabat/bins/ -d envs/share/catbat/database/ -t envs/share/catbat/taxonomy/ -o test1/BAT_run

Bin folder: data/metabat/bins/
Taxonomy folder: envs/share/catbat/taxonomy/
Database folder: envs/share/catbat/database/
Parameter r: 10.0
Parameter f: 0.1
Log file: test1/BAT_run.log

-----------------

Doing some pre-flight checks first.
[2020-02-20 09:11:32.640270] Prodigal found: Prodigal V2.6.3: February, 2016.
[2020-02-20 09:11:32.978950] DIAMOND found: diamond version 0.9.14.
Ready to fly!

-----------------

[2020-02-20 09:11:32.990032] Importing bins from data/metabat/bins/.
[2020-02-20 09:16:30.119352] 6342 bin(s) found!
[2020-02-20 09:16:30.124320] Writing test1/BAT_run.concatenated.fasta.
[2020-02-20 09:16:36.237435] Running Prodigal for ORF prediction. Files test1/BAT_run.concatenated.predicted_proteins.faa and test1/BAT_run.concatenated.predicted_proteins.gff will be generated. Do not forget to cite Prodigal when using CAT or BAT in your publication!
[2020-02-20 09:55:27.250312] ORF prediction done!
[2020-02-20 09:55:27.256219] Parsing ORF file test1/BAT_run.concatenated.predicted_proteins.faa
[2020-02-20 09:55:28.086029] Homology search with DIAMOND is starting. Please be patient. Do not forget to cite DIAMOND when using CAT or BAT in your publication!
				query: test1/BAT_run.concatenated.predicted_proteins.faa
				database: envs/share/catbat/database/refseq_viral.dmnd
				mode: sensitive
				number of cores: 4
				block-size (billions of letters): 6.0
				index-chunks: 1
				tmpdir: test1
				top: 50
[2020-02-20 10:00:39.372717] Homology search done! File test1/BAT_run.concatenated.alignment.diamond created.
[2020-02-20 10:00:39.374596] Parsing DIAMOND file test1/BAT_run.concatenated.alignment.diamond.
[2020-02-20 10:00:41.020247] Importing file envs/share/catbat/taxonomy/nodes.dmp.
[2020-02-20 10:00:46.049918] Importing file envs/share/catbat/database/2020-02-19.nr.fastaid2LCAtaxid.
[2020-02-20 10:00:46.227850] Importing file envs/share/catbat/database/2020-02-19.nr.taxids_with_multiple_offspring.
[2020-02-20 10:00:46.239088] BAT is flying! Files test1/BAT_run.bin2classification.txt and test1/BAT_run.ORF2LCA.txt are created.
Traceback (most recent call last):
  File "/home/wlclose/miniconda3/envs/catbat/bin/CAT", line 76, in <module>
    main()
  File "/home/wlclose/miniconda3/envs/catbat/bin/CAT", line 62, in main
    bins.run()
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/bins.py", line 693, in run
    bins(args)
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/bins.py", line 605, in bins
    starred_lineage = tax.star_lineage(lineage,
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/tax.py", line 145, in star_lineage
    questionable_taxids = find_questionable_taxids(lineage,
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/tax.py", line 137, in find_questionable_taxids
    taxid_parent = lineage[i + 1]
IndexError: list index out of range
```

**Comment by wclose** [comment]
After looking into it some more, it appears to be triggering the error when the tax lineage only has two levels. Any more or less than that and it's fine.

**Comment by wclose** [comment]
I was able to make a slight workaround by modifying bins.py and replacing all assignments to `starred_lineage` with `starred_lineage = tax.find_lineage(taxid, taxid2parent)` which allows me to skip the problematic step. While this works ok, it would be nice not to have to modify the source script. It could also be useful to have an argument that allows you to turn on/off the asterisks because for what I'm working on, I actually don't need/want them anyways.

**Comment by wclose** [comment]
I also ran into a similar index error when using the `CAT add_names` and `CAT add_names --only-official`. Here's an example log for each of those:
```
# CAT v5.0.3.
[2020-02-21 00:24:28.255713] Importing file envs/share/catbat/taxonomy/nodes.dmp.
[2020-02-21 00:24:30.640879] Importing file envs/share/catbat/taxonomy/names.dmp.
[2020-02-21 00:24:33.108948] Appending names...
Traceback (most recent call last):
  File "/home/wlclose/miniconda3/envs/catbat/bin/CAT", line 76, in <module>
    main()
  File "/home/wlclose/miniconda3/envs/catbat/bin/CAT", line 64, in main
    add_names.run()
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/add_names.py", line 210, in run
    add_names(args)
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/add_names.py", line 196, in add_names
    names = tax.convert_to_names(lineage,
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/tax.py", line 241, in convert_to_names
    names.append('{0} ({1}): {2}'.format(name, rank, scores[i]))
IndexError: list index out of range
```
```
# CAT v5.0.3.
[2020-02-21 00:37:23.393957] Importing file envs/share/catbat/taxonomy/nodes.dmp.
[2020-02-21 00:37:25.711696] Importing file envs/share/catbat/taxonomy/names.dmp.
[2020-02-21 00:37:27.578841] Appending names...
Traceback (most recent call last):
  File "/home/wlclose/miniconda3/envs/catbat/bin/CAT", line 76, in <module>
    main()
  File "/home/wlclose/miniconda3/envs/catbat/bin/CAT", line 64, in main
    add_names.run()
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/add_names.py", line 210, in run
    add_names(args)
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/add_names.py", line 191, in add_names
    names = tax.convert_to_official_names(lineage,
  File "/home/wlclose/miniconda3/envs/catbat/share/cat-5.0.3-0/CAT_pack/tax.py", line 280, in convert_to_official_names
    official_names[i] = '{0}: {1}'.format(name, scores[index])
IndexError: list index out of range
```

**Comment by bastiaanvonmeijenfeldt** [comment]
I have added the `--no_stars` flag in v5.0.4, which allows you to suppress the assignment of asterisks to the lineage. Hope this helps!

Best wishes,

Bastiaan

**Comment by wclose** [comment]
Excellent! Thanks, @bastiaanvonmeijenfeldt !
