### ISSUE TITLE
Error in downloading database

### ISSUE THREAD

**Issue by bingxue-98** [dutilh/CAT#46]
Hello,
There is an error when downloading database by the following commands:
```
$ CAT prepare --fresh 
$ CAT prepare --existing -d {folder containing nr} -t {folder containing taxonomy files}
```
File fastaid2LCAtaxid and taxids_with_multiple_offspring can't be created because of a memory error.

```
Doing some pre-flight checks first.
[2020-12-20 21:50:34.879804] DIAMOND found: diamond version 2.0.5.
[2020-12-20 21:50:34.881043] Taxonomy folder found.
[2020-12-20 21:50:34.881699] Nodes.dmp found: /lustre/home/liutang/01software/cat_5.2/2020-12-19_taxonomy/nodes.dmp.
[2020-12-20 21:50:34.882206] Names.dmp found: /lustre/home/liutang/01software/cat_5.2/2020-12-19_taxonomy/names.dmp.
[2020-12-20 21:50:34.882683] Prot.accession2taxid file found: /lustre/home/liutang/01software/cat_5.2/2020-12-19_taxonomy/2020-12-19.prot.accession2taxid.gz.
[2020-12-20 21:50:34.883191] Database folder found.
[2020-12-20 21:50:34.883646] Nr file found: /lustre/home/liutang/01software/cat_5.2/2020-12-19_CAT_database/2020-12-19.nr.gz.
[2020-12-20 21:50:34.884077] DIAMOND database found: /lustre/home/liutang/01software/cat_5.2/2020-12-19_CAT_database/2020-12-19.nr.dmnd.
[2020-12-20 21:50:34.884510] File fastaid2LCAtaxid will be created.
[2020-12-20 21:50:34.884934] File taxids_with_multiple_offspring will be created.
Ready to fly!

-----------------

[2020-12-20 21:50:34.886539] Loading /lustre/home/liutang/01software/cat_5.2/2020-12-19_taxonomy/2020-12-19.prot.accession2taxid.gz into memory. Please be patient...
Traceback (most recent call last):
  File "/lustre/home/liutang/.conda/envs/cat_5.2/bin/CAT", line 84, in <module>
    main()
  File "/lustre/home/liutang/.conda/envs/cat_5.2/bin/CAT", line 62, in main
    prepare.run()
  File "/lustre/home/liutang/.conda/envs/cat_5.2/share/cat-5.1.2-0/CAT_pack/prepare.py", line 815, in run
    run_existing(args)
  File "/lustre/home/liutang/.conda/envs/cat_5.2/share/cat-5.1.2-0/CAT_pack/prepare.py", line 804, in run_existing
    prepare(step_list, args)
  File "/lustre/home/liutang/.conda/envs/cat_5.2/share/cat-5.1.2-0/CAT_pack/prepare.py", line 437, in prepare
    make_fastaid2LCAtaxid_file(
  File "/lustre/home/liutang/.conda/envs/cat_5.2/share/cat-5.1.2-0/CAT_pack/prepare.py", line 269, in make_fastaid2LCAtaxid_file
    prot_accession2taxid = import_prot_accession2taxid(
  File "/lustre/home/liutang/.conda/envs/cat_5.2/share/cat-5.1.2-0/CAT_pack/prepare.py", line 257, in import_prot_accession2taxid
    prot_accession2taxid[line[1]] = line[2]
MemoryError
```
Can you help me to solve this problem? Thanks.

**Comment by Finesim97** [comment]
You are running out of memory, how much unallocated memory is available, before you run CAT? The command to determine that is `free -h`

**Comment by bingxue-98** [comment]
I checked the unallocated memory and retried the commond.
`              total        used        free      shared  buff/cache   available
Mem:           187G         24G         82G         16M         80G        152G
Swap:           31G        1.7G         29G
`
` CAT prepare --existing -d {folder containing nr} -t {folder containing taxonomy files}`
The same error occurred again.

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @bingxue-98 , 

CAT prepare needs about 200GB available memory. The bottleneck is the loading of the accession2taxid file, we're aware of this and thinking of ways to make it more efficient in terms of memory management.
In the meantime if you cannot find a computer with enough memory, you can download a preconstructed database from https://tbb.bio.uu.nl/bastiaan/CAT_prepare/. I will create a new one in the new year.

Hope this helps!

Bastiaan

**Comment by bingxue-98** [comment]
Hi @bastiaanvonmeijenfeldt ,
I've solved this problem by your help. Thank you so much!
