### ISSUE TITLE
TypeError with add-names

### ISSUE THREAD

**Issue by mmishra403** [dutilh/CAT#68]
hello! I'm trying to add names to my CAT contigs output file, but I keep getting the following error when I run add_names:

Loading file None.
Traceback (most recent call last):
  File "/scratch/gpfs/mmishra/CONDA/envs/cat/bin/CAT", line 84, in <module>
    main()
  File "/scratch/gpfs/mmishra/CONDA/envs/cat/bin/CAT", line 70, in main
    add_names.run()
  File "/scratch/gpfs/mmishra/CONDA/envs/cat/share/cat-5.2.3-1/CAT_pack/add_names.py", line 73, in run
    args.nodes_dmp, args.log_file, args.quiet)
  File "/scratch/gpfs/mmishra/CONDA/envs/cat/share/cat-5.2.3-1/CAT_pack/tax.py", line 15, in import_nodes
    with open(nodes_dmp, 'r') as f1:
**TypeError: expected str, bytes or os.PathLike object, not NoneType**

This is the command I'm running, and the input file looks okay:
CAT add_names -i BSL_C1_Rep1_B18-tax-out.tmp.ORF2LCA.txt -o BSL_C1_Rep1_B18-gene-tax-out.tmp -t ../CAT_prepare_20210107/2021-01-17_taxonomy --only_official

any help would be greatly appreciated! i'm new to microbiome analysis and a novice coder, so apologies if this is a basic question. thank you!

**Comment by sheaster** [comment]
did you manage to solve this?
